### ISSUE TITLE
TLC Shapefile

### ISSUE THREAD

**Issue by aniquetahir** [toddwschneider/nyc-taxi-data#27]
I have a question about the shapefile. Apparently the coordinates in the shapefile do not match the actual latitude longitude.

**Comment by toddwschneider** [comment]
@aniquetahir what is your question? If you think there's an error in the shapefile, can you point to a specific example? Thanks

**Comment by aniquetahir** [comment]
When I load the TLC shapefile into QGIS. It doesn't give me coordinates in the form of longitude and latitude. But if I use the provided scripts to load the data into postgis, it works fine. I was just curious about the projection that was used. The provided scripts appear to be working fine

**Comment by toddwschneider** [comment]
The shapefile's projection is [EPSG:2263](http://spatialreference.org/ref/epsg/2263/html/)

Here's the line that converts it to EPSG:4326 in PostGIS: https://github.com/toddwschneider/nyc-taxi-data/blob/master/initialize_database.sh#L7

I'm going to close this issue since it sounds like it's a question for QGIS
