### ISSUE TITLE
is there a checksum for download validation?

### ISSUE THREAD

**Issue by amosbird** [toddwschneider/nyc-taxi-data#28]
Hi, i've been downloading this dataset for a week. I wonder if there is a way to validate the data files after downloading.

**Comment by toddwschneider** [comment]
@amosbird a week sounds like way too long for the download. Can you try on a single file? I'd recommend a `green_` file since they are smaller

You could also try downloading from the TLC website here: http://www.nyc.gov/html/tlc/html/about/trip_record_data.shtml, or Google BigQuery here: https://cloud.google.com/bigquery/public-data/nyc-tlc-trips (I have never worked with the BigQuery data so am not sure if it's the same)

I don't know of any good way to validate the data, but in total it should be over 300 GB

**Comment by amosbird** [comment]
well i double checked all my data files with `wget -c` . it seems the total size is 221 GB. Is that correct?

**Comment by toddwschneider** [comment]
@amosbird I do not know the total file size off the top of my head, but that sounds believable. The database will be over 300 GB, but that includes additional columns plus a primary key index

Maybe you could `curl -I` each file, check the `Content-Length`, and add those values up to get the estimated total raw file size?

**Comment by amosbird** [comment]
good idea. thanks!
