### ISSUE TITLE
How to get shapefile for NYC census tracts and neighborhood tabulation areas?

### ISSUE THREAD

**Issue by sjtuztq** [toddwschneider/nyc-taxi-data#45]
How to get shapefile for NYC census tracts and neighborhood tabulation areas?I can get  PULocation ID and DOLocation ID,but I can't get the actual location information.

**Comment by toddwschneider** [comment]
The shapefiles are included in the repo:

- [Census tracts & NTAs](https://github.com/toddwschneider/nyc-taxi-data/tree/master/shapefiles/nyct2010_15b)
- [Taxi zones](https://github.com/toddwschneider/nyc-taxi-data/tree/master/shapefiles/taxi_zones)

If you want to download them yourself you can also find them on these NYC websites:

1. https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page
2. https://www1.nyc.gov/site/planning/data-maps/open-data/districts-download-metadata.page

Note that latitude/longitude are only available for taxi trips before July 2016. Since July 2016, the data only includes taxi zone location IDs

I'm going to close this issue, but let me know if there's anything else. Thanks
